### ISSUE TITLE
Strange display behavior with the "y" key

### ISSUE THREAD

**Issue by fabrice0878** [Antonioya/blender#16] opened 2015-11-12 11:44 UTC
With blender 2.76b in edit mode, when i press the "y" key, all the measurements switch in another location....
before :
![before](https://cloud.githubusercontent.com/assets/15815628/11117550/fb713eb8-893a-11e5-8f96-17950fb11167.jpg)

After :
![after](https://cloud.githubusercontent.com/assets/15815628/11117553/069fab6c-893b-11e5-8b17-72afe11aead8.jpg)

**Comment by fabrice0878** [comment] 2015-11-12 11:45
And, by the way.. Thank you for this wonderful add-on !  :)

**Comment by fabrice0878** [comment] 2015-11-12 12:02
(measureit v.1.6.2)

**Comment by Antonioya** [comment] 2015-11-12 17:18
I have Windows 2.76b and pressing Y key in edit mode doesn't change anything. Do you have any other add-on or custom key?

**Comment by fabrice0878** [comment] 2015-11-16 10:20
Hello,

I have no custom key and the only add-on i've got are, for "Mesh" : 3Dprint Toolbox; in "import-export" : ADS, BHV, FBX, STL, SVG, PLY, UV Layout, OBJ, X3D/VRML2 and in "render" : Cycles.

I tried again today and the strange thing is that it's working now. No more measure displacement. I don't really understand what happened...

Thank you.


----- Mail original -----
De: "Antonioya" <notifications@github.com>
À: "Antonioya/blender" <blender@noreply.github.com>
Cc: "fabrice0878" <fabtetard@free.fr>
Envoyé: Jeudi 12 Novembre 2015 18:18:35
Objet: Re: [blender] Strange display behavior with the "y" key (#16)



I have Windows 2.76b and pressing Y key in edit mode doesn't change anything. Do you have any other add-on or custom key?

**Comment by Antonioya** [comment] 2015-12-06 17:43
Unable to reproduce. I'm going to close the issue.

**Closed by Antonioya** 2015-12-06 17:43 UTC
